/* ============================================================
   Bake recorded fart samples into a JS module.

   ⚠ THIS IS THE ONE PLACE THE PROJECT SHIPS RECORDED AUDIO.
   Everything else in this game — every mesh, every note of
   music, every other sound effect — is computed at runtime, and
   the README says so. Fart mode is the deliberate exception,
   because a real recording is funnier than a synthesised one and
   that is the entire point of the feature. Do not take this file
   as licence to add samples anywhere else.

   Usage:
     node tools/bake-farts.mjs <files-or-dir...> [--kbps=40] [--rate=22050]
     node tools/bake-farts.mjs --clear        # remove the samples again

   ⚠ IT SPLITS COMPILATION CLIPS AUTOMATICALLY. Sample packs
   almost always arrive as one file holding a dozen farts in a
   row separated by silence, so by default every input is run
   through ffmpeg's `silencedetect` and cut into one sample per
   burst. That is also why sorting matters — a compilation
   contains both a half-second squeak and a three-second
   trombone, and split apart those land at opposite ends of the
   size ladder automatically. `--no-split` treats each file as a
   single sample instead.

   Accepts anything ffmpeg can read: .wav .mp3 .m4a .ogg .opus
   .aac .flac, a phone voice memo, whatever. Per clip it:

     1. downmixes to mono — stereo doubles the size and a fart is
        a point source anyway;
     2. trims leading and trailing silence, because a voice memo
        is mostly the sound of somebody reaching for the phone;
     3. peak-normalises, so one quiet recording in the set does
        not vanish under the others;
     4. resamples to 22.05kHz — there is essentially nothing above
        5kHz in this material and halving the rate halves the bill;
     5. encodes MP3 mono.

   MP3 RATHER THAN OPUS, deliberately. Opus is better per byte,
   but `decodeAudioData` support for Opus-in-Ogg has historically
   been patchy in Safari, and this whole feature is a joke — a
   joke that silently fails on someone's iPhone is worse than one
   that costs three extra kilobytes.

   Output is `src/audio/fartSamples.js`, base64 in a plain module,
   which the single-file build then inlines exactly the way it
   already inlines the six woff2 fonts. No new build machinery.
   ============================================================ */

import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const OUT = path.join(ROOT, 'src', 'audio', 'fartSamples.js');

const argv = process.argv.slice(2);
const KBPS = +(argv.find((a) => a.startsWith('--kbps='))?.slice(7) || 40);
const RATE = +(argv.find((a) => a.startsWith('--rate='))?.slice(7) || 22050);
const SPLIT = !argv.includes('--no-split');
/** dB below full scale that counts as silence between bursts. */
const SIL_DB = +(argv.find((a) => a.startsWith('--silence='))?.slice(10) || -38);
/** How long a quiet patch has to be before it separates two samples.
 *  0.12s: shorter and a single sputtery fart gets chopped into three. */
const SIL_MIN = +(argv.find((a) => a.startsWith('--gap='))?.slice(6) || 0.12);
const inputs = argv.filter((a) => !a.startsWith('--'));

const HEADER = `/* ============================================================
   GENERATED by tools/bake-farts.mjs — DO NOT EDIT BY HAND.
   Re-run the tool to change these.

   The one exception to "there are no asset files" in this
   project. See the tool's header for why, and do not treat it
   as a precedent.
   ============================================================ */\n\n`;

if (argv.includes('--clear')) {
  fs.writeFileSync(OUT, `${HEADER}export const FART_SAMPLES = [];\n`);
  console.log('cleared — fart mode falls back to the procedural voice');
  process.exit(0);
}

if (!inputs.length) {
  console.error('usage: node tools/bake-farts.mjs <files-or-dir...> [--kbps=40] [--rate=22050]');
  console.error('       node tools/bake-farts.mjs --clear');
  process.exit(1);
}

/* Expand directories one level. Recursing would sweep up whatever else is in a
   Downloads folder, and a silent surprise in a generated file is worse than
   making the caller name a directory. */
const files = [];
for (const inp of inputs) {
  const p = path.resolve(inp);
  if (!fs.existsSync(p)) { console.error(`no such path: ${p}`); process.exit(1); }
  if (fs.statSync(p).isDirectory()) {
    for (const f of fs.readdirSync(p).sort()) {
      if (/\.(wav|mp3|m4a|ogg|opus|aac|flac|aiff?|caf|webm)$/i.test(f)) files.push(path.join(p, f));
    }
  } else files.push(p);
}
if (!files.length) { console.error('no audio files found'); process.exit(1); }

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'farts-'));
const ff = (args) => execFileSync('ffmpeg', ['-y', '-loglevel', 'error', ...args], { stdio: ['ignore', 'pipe', 'pipe'] });
const probeDur = (f) => parseFloat(execFileSync('ffprobe',
  ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f]).toString().trim());

/**
 * Cut one file into its individual bursts.
 *
 * ffmpeg's `silencedetect` reports quiet PERIODS to stderr; the samples are the
 * gaps between them, which is the inversion nobody gets right first time. Two
 * details that matter:
 *
 *  - A file that starts loud has no leading silence report, and one that ends
 *    loud has no trailing `silence_end`. So the first segment starts at 0 unless
 *    told otherwise, and the last runs to EOF.
 *  - A tiny pad is added either side. Cutting exactly on the threshold crossing
 *    clips the attack transient, and the attack is most of what makes a fart
 *    read as a fart rather than as a hum.
 */
function findBursts(src) {
  const total = probeDur(src);
  if (!SPLIT) return [{ start: 0, dur: total }];
  /* spawnSync, NOT execFileSync. `silencedetect` writes its findings to STDERR
     and ffmpeg then exits 0 — and execFileSync returns only stdout on success,
     so the first version of this read an empty string, found no silence, and
     reported every compilation as a single three-second "burst". It looked
     like the splitter was working and doing nothing. */
  const res = spawnSync('ffmpeg', ['-i', src, '-af',
    `silencedetect=noise=${SIL_DB}dB:d=${SIL_MIN}`, '-f', 'null', '-'],
  { encoding: 'utf8' });
  const log = `${res.stderr || ''}${res.stdout || ''}`;

  const quiet = [];
  const re = /silence_start:\s*(-?[\d.]+)|silence_end:\s*(-?[\d.]+)/g;
  let m, open = null;
  while ((m = re.exec(log))) {
    if (m[1] !== undefined) open = Math.max(0, parseFloat(m[1]));
    else if (open !== null) { quiet.push([open, parseFloat(m[2])]); open = null; }
    else quiet.push([0, parseFloat(m[2])]);          // file opened in silence
  }
  if (open !== null) quiet.push([open, total]);       // file ended in silence

  const PAD = 0.02;
  const out = [];
  let cursor = 0;
  for (const [qs, qe] of quiet) {
    if (qs - cursor > 0.05) out.push({ start: Math.max(0, cursor - PAD), dur: (qs - cursor) + PAD * 2 });
    cursor = qe;
  }
  if (total - cursor > 0.05) out.push({ start: Math.max(0, cursor - PAD), dur: (total - cursor) + PAD });
  return out.length ? out : [{ start: 0, dur: total }];
}

console.log(`baking at ${RATE}Hz mono, ${KBPS}kbps mp3` +
  `${SPLIT ? `, splitting on ${SIL_MIN}s of silence below ${SIL_DB}dB` : ', one sample per file'}\n`);

/* Expand every input into its bursts BEFORE processing, so the log reads as a
   list of samples rather than a list of files. */
const clips = [];
for (const src of files) {
  const bursts = findBursts(src);
  const stem = path.basename(src).replace(/\.[^.]+$/, '');
  console.log(`  ${stem}: ${bursts.length} burst(s)`);
  bursts.forEach((b, i) => clips.push({
    src, ...b, name: bursts.length > 1 ? `${stem}#${i + 1}` : stem,
  }));
}
console.log('');

const baked = [];
for (const clip of clips) {
  const { src, name } = clip;
  const mp3 = path.join(tmp, `${baked.length}.mp3`);
  try {
    ff([
      '-ss', String(clip.start), '-t', String(clip.dur),
      '-i', src,
      '-ac', '1',
      '-ar', String(RATE),
      /* Trim both ends. `-90dB` rather than `0` because a phone recording has a
         noise floor and an absolute-zero threshold trims nothing at all.
         `areverse` twice is the standard way to apply a start-trim to the end. */
      '-af', [
        'silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.02',
        'areverse',
        'silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.02',
        'areverse',
        // Peak-normalise so one shy recording does not disappear behind the rest.
        'dynaudnorm=p=0.9:s=5',
        'alimiter=limit=0.95',
      ].join(','),
      '-c:a', 'libmp3lame', '-b:a', `${KBPS}k`,
      mp3,
    ]);
  } catch (e) {
    console.error(`  SKIP ${name}: ffmpeg failed — ${String(e.stderr || e).slice(0, 120)}`);
    continue;
  }
  const bytes = fs.readFileSync(mp3);
  const dur = probeDur(mp3);
  if (!isFinite(dur) || dur < 0.05) {
    console.error(`  SKIP ${name}: ${dur}s after trimming — probably silence`);
    continue;
  }
  /* DEDUPE. Sample packs routinely ship the same clip under two names — this
     set arrived with `dry-fart.mp3` and `dry-fart_3.mp3` byte-identical. A
     duplicate is not harmless: selection is uniform within a class, so a
     doubled sample plays twice as often as its neighbours and is the first one
     the player starts recognising. Hashed AFTER encoding, so two different
     source formats of the same recording also collapse. */
  const hash = createHash('md5').update(bytes).digest('hex');
  const twin = baked.find((b) => b.hash === hash);
  if (twin) {
    console.log(`  ${name.padEnd(24)} duplicate of ${twin.name} — skipped`);
    continue;
  }
  if (dur > 3) console.warn(`  WARN ${name}: ${dur.toFixed(2)}s is long for a pickup sound`);
  baked.push({ name, dur, hash, b64: bytes.toString('base64'), kb: bytes.length / 1024 });
  console.log(`  ${name.padEnd(24)} ${dur.toFixed(3)}s  ${(bytes.length / 1024).toFixed(1)} KB`);
}

if (!baked.length) { console.error('\nnothing baked'); process.exit(1); }

/* SORTED SHORT TO LONG, then cut into CLASSES.
   Length is the only property of a recording that reliably tracks "how big does
   this sound", so rank by it and split the ranking into bands. Classes rather
   than a continuous index because the point is to have SEVERAL candidates at
   any given item size — one sample per size is one sound the player memorises,
   and the whole reason for using recordings is that they are more varied than
   the synth, which is only true if more than one can turn up. */
baked.sort((a, b) => a.dur - b.dur);

/* Terciles by COUNT, not by duration. Splitting on duration would put nine
   samples in "small" and one in "large" the moment somebody contributes a
   four-second trombone, and a class of one is a class the player learns. */
const CLASS_NAMES = ['small', 'medium', 'large'];
const per = baked.length / CLASS_NAMES.length;
baked.forEach((s, i) => { s.cls = Math.min(CLASS_NAMES.length - 1, Math.floor(i / per)); });

const body = baked.map((s) =>
  `  // ${CLASS_NAMES[s.cls].padEnd(6)} ${s.name} — ${s.dur.toFixed(3)}s, ${s.kb.toFixed(1)} KB\n` +
  `  { dur: ${s.dur.toFixed(3)}, cls: ${s.cls}, mp3: '${s.b64}' },`).join('\n');

const totalKb = baked.reduce((n, s) => n + s.kb, 0);
const counts = CLASS_NAMES.map((_, c) => baked.filter((s) => s.cls === c).length);

fs.writeFileSync(OUT,
  `${HEADER}` +
  `/* ${baked.length} samples, sorted SHORT to LONG and banded into classes.\n` +
  `   ${CLASS_NAMES.map((n, c) => `${n} ${counts[c]}`).join(', ')}.\n` +
  `   ${totalKb.toFixed(1)} KB of mp3, roughly ${(totalKb * 1.34).toFixed(1)} KB once\n` +
  `   base64'd into the single-file build.\n\n` +
  `   \`cls\` is what Sfx.fart selects on: item size picks the CLASS, then one\n` +
  `   member of it at random. Both the order and the class field are\n` +
  `   load-bearing — re-run the bake tool rather than editing either. */\n` +
  `export const FART_CLASSES = ${JSON.stringify(CLASS_NAMES)};\n` +
  `export const FART_SAMPLES = [\n${body}\n];\n`);

console.log(`\nwrote ${path.relative(ROOT, OUT)}`);
console.log(`  ${baked.length} samples, ${totalKb.toFixed(1)} KB mp3 → ~${(totalKb * 1.34).toFixed(1)} KB base64`);
console.log(`  shortest ${baked[0].dur.toFixed(3)}s → longest ${baked[baked.length - 1].dur.toFixed(3)}s`);
for (let c = 0; c < CLASS_NAMES.length; c++) {
  const inC = baked.filter((s) => s.cls === c);
  console.log(`  ${CLASS_NAMES[c].padEnd(6)} ${String(inC.length).padStart(2)} samples  ` +
    `${inC[0].dur.toFixed(2)}s–${inC[inC.length - 1].dur.toFixed(2)}s   ${inC.map((s) => s.name).join(', ')}`);
}
console.log(`\nnow: npm run build && npm run single`);

fs.rmSync(tmp, { recursive: true, force: true });
