/* ============================================================
   Claudemary LLMaci — entry point.

   A browser recreation of the classic katamari-rolling game.
   Every mesh, every note and every sound effect in here is
   generated by this code at runtime; there are no external
   assets of any kind.
   ============================================================ */

import { Game } from './core/Game.js';
import { TUNING } from './world/Katamari.js';
import * as quips from './ui/quips.js';

const canvas = document.getElementById('scene');

function fitCanvas() {
  canvas.style.width = '100%';
  canvas.style.height = '100%';
  canvas.width = canvas.clientWidth;
  canvas.height = canvas.clientHeight;
}
fitCanvas();

const game = new Game(canvas);
window.__katamari = game;   // handy for poking at things from the console
window.__llmaci = game;
game.tuning = TUNING;            // live tuning, for the console and the harness
game.__quips = quips;            // debug handle for the quip harness
window.__quipPool = [...quips.CHEERS, ...quips.BIG_CATCH, ...quips.KNOCKS];

console.log(
  '%c Claudemary LLMaci ',
  'background:#6b46c1;color:#ffd93b;font-size:18px;font-weight:bold;padding:6px 10px;border-radius:6px',
);
console.log(
  '%cEverything here — every mesh, every note, every sound — is generated at runtime.\n' +
  'Nothing is loaded from disk. Try window.__llmaci.kat.attached.length mid-roll.',
  'color:#4a90d9',
);

game.boot().catch((err) => {
  console.error(err);
  const el = document.getElementById('loading-text');
  if (el) {
    el.textContent = 'Something went wrong starting up — check the console.';
    el.style.fontSize = '18px';
  }
});
